max_steps = 500
batch_size = 1024
micro_batch_size = 1
seq_len = 8192
rollouts_per_example = 8

[sampling]
temperature = 0.6
max_tokens = 8192

[model]
name = "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

[environment]
id = "deepscaler"

[ckpt]
interval = 100