[model]
name = "willcb/DeepSeek-R1-Distill-Qwen-1.5B"
max_model_len = 8192  # Match the seq_len in orchestrator config

# Increase GPU memory utilization for more KV cache
gpu_memory_utilization = 0.95  # Increased from default 0.9

[parallel]
dp = 6