max_steps = 500
batch_size = 1024
micro_batch_size = 1
seq_len = 4096
rollouts_per_example = 32
mask_truncated_completions = true

[model]
name = "willcb/Qwen3-14B"

[wandb]
project = "wordle"

[environment]
id = "wordle"

[environment.args]

[sampling]
max_tokens = 1024

[wandb.log_extras]
interval = 10

[ckpt]